apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  # property-like keys; each key maps to a simple value
  workshop-name: tunisian-gangsters
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-configs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: busybox:latest
          command: ["tail", "-f", "/dev/null"]
          envFrom:
            - configMapRef:
                name: configs
          

