apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: apple-container
      image: hashicorp/http-echo
      args:
        - "-text=apple"
        - "-listen=:8082"
      ports:
        - name: http-port
          containerPort: 8082


    - name: orange-container
      image: hashicorp/http-echo
      args:
        - "-listen=:8081"
        - "-text=orange"
      ports:
        - name: http-port
          containerPort: 8081
    
    - name: shell
      image: alpine
      command: ["tail", "-f", "/dev/null"]
      ports:
        - name: http-port
          containerPort: 8083
