apiVersion: v1
kind: Pod
metadata:
  name: echo-pod
spec:
  containers:
    - name: echo-server
      image: hashicorp/http-echo
      args:
        - "-text=apple"
      ports:
        - name: http-port
          containerPort: 5678
