apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
stringData:
  secret-file: username3

# data:
#   secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-secret
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      # volumes:
      #   - name: secret-volume
      #     secret:
      #       secretName: dotfile-secret
      containers:
      - name: shell
        image: alpine
        command:
          - tail
          - "-f"
          - "/dev/null"
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: dotfile-secret
                key: secret-file
        # volumeMounts:
        # - name: secret-volume
        #   readOnly: true
        #   mountPath: "/etc/secret-volume"