apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-deployment
spec:
  selector:
    matchLabels:
      app: apple-server
  template:
    metadata:
      labels:
        app: apple-server
    spec:
      containers:
        - name: apple-server
          image: hashicorp/http-echo
          args:
            - "-text=apple"
          ports:
            - name: http-port
              containerPort: 5678
---

apiVersion: v1
kind: Service
metadata:
  name: apple-service
spec:
  selector:
    app: apple-server
  ports:
    - port: 5678

